dbtlearn:
  outputs:
    dev:
      account: 'your-account'
      database: 'your-db'
      password: 'your-password'
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
